import Mathlib

open MvPolynomial

noncomputable section

/-- The ideal I generated by the products X(2*k) * X(2*k+1) for k : ℕ in the polynomial
ring MvPolynomial ℕ ℤ. -/
def I : Ideal (MvPolynomial ℕ ℤ) :=
  Ideal.span (Set.range fun k : ℕ => MvPolynomial.X (2 * k) * MvPolynomial.X (2 * k + 1))

/-- Exercise: The quotient ring Z[x1,x2,...]/(x1 x2, x3 x4, x5 x6, ...) has infinitely many minimal prime ideals.
We state this as the existence of an infinite family of distinct prime ideals of MvPolynomial ℕ ℤ containing I
and minimal among primes containing I. -/
theorem Dummit_Foote_exercise_9_1_10 :
  ∃ (P : ℕ → Ideal (MvPolynomial ℕ ℤ)),
    (∀ n, Ideal.IsPrime (P n) ∧ I ≤ P n ∧ (∀ Q, Ideal.IsPrime Q → I ≤ Q → Q ≤ P n → Q = P n)) ∧
    Function.Injective P := by sorry

end noncomputable section