import Mathlib

/-
  We model Z[i] as the quotient of the polynomial ring Z[X] by the ideal (X^2 + 1).
  The exercise: let q be a prime with q ≡ 3 (mod 4). Prove that Z[i]/(q) is a field with q^2 elements.

  The statement below translates the assertion into Lean. As requested, the proof is omitted
  and replaced by `by sorry`.
-/

open Polynomial

def Z_i : Type := (Polynomial Int) ⧸ Ideal.span ({X ^ 2 + 1} : Set (Polynomial Int))

/--
The quotient ring Z[i]/(q) is a field of order q^2 when q is a prime ≡ 3 (mod 4).
We state the result for q : ℕ with q.Prime and q % 4 = 3. The ideal (q) is understood
as the ideal of Z[i] generated by the image of q under the canonical map Int → Z[i].
-/
theorem Dummit_Foote_exercise_8_3_6b (q : ℕ) (hq : q.Prime) (hmod : q % 4 = 3) :
  -- the quotient ring Z[i]/(q) is a field
  IsField (Z_i ⧸ Ideal.span ({(q : Z_i)} : Set Z_i)) ∧
  -- it is finite and has q^2 elements
  Fintype (Z_i ⧸ Ideal.span ({(q : Z_i)} : Set Z_i)) ∧
  Fintype.card (Z_i ⧸ Ideal.span ({(q : Z_i)} : Set Z_i)) = q ^ 2 := by sorry
