import Mathlib

/-- If H is a subgroup of G, then H is generated by H \ {1}. -/
theorem subgroup_generated_by_remove_one {G : Type _} [Group G] (H : Subgroup G) :
  Subgroup.closure ((H : Set G) \ {1 : G}) = H := by sorry
