import Mathlib

open Subgroup

/-- If a group G has elements a, b with a^5 = 1, b^2 = 1 and ba = a^2 b,
then the subgroup generated by a and b is (multiplicatively) isomorphic to
Multiplicative (ZMod 2), i.e. a cyclic group of order 2. -/
theorem srdoty_alg_present_315 {G : Type*} [Group G] {a b : G}
  (ha : a ^ 5 = 1) (hb : b ^ 2 = 1) (hrel : b * a = a ^ 2 * b) :
  (Subgroup.closure ({a, b} : Set G) : Type) ≃* Multiplicative (ZMod 2) := by sorry
