import Mathlib
open Set
open Subgroup

/-- Prove that if `H` is a subgroup of `G` then `H` is generated by the set `H - {1}`. -/
theorem generated_subgroup_by_set_minus_one_extracted {G : Type*} [Group G] (H : Subgroup G) : Subgroup.closure (↑H \ {1}) = H := by sorry
