import Mathlib

/-!
Show that if 𝒜 is a basis for a topology on X, then the topology
generated by 𝒜 equals the intersection of all topologies on X that
contain 𝒜.
-/

theorem Munkres_exercise_13_5a {X : Type _} (A : Set (Set X))
  (basis_axiom1 : ∀ x : X, ∃ B ∈ A, x ∈ B)
  (basis_axiom2 : ∀ B1 ∈ A, ∀ B2 ∈ A, ∀ x ∈ B1 ∩ B2, ∃ B3 ∈ A, x ∈ B3 ∧ B3 ⊆ B1 ∩ B2) :
  TopologicalSpace.generateFrom A =
    ⨅ (t : { t : TopologicalSpace X // ∀ U ∈ A, @TopologicalSpace.IsOpen X t U }), (t : TopologicalSpace X) := by
  sorry
