import Mathlib

open Set

variable {G : Type*} [Group G]

/-- If H is a subgroup of G then H is generated by H \ {1}. -/
theorem Dummit_Foote_exercise_2_4_4 (H : Subgroup G) :
  H = Subgroup.closure ((H : Set G) \ { (1 : G) }) := by sorry
