import Mathlib

/-- The collection of all open intervals with rational endpoints as subsets of ℝ. -/
def rational_open_intervals : Set (Set ℝ) :=
  { s | ∃ (a b : ℚ), (a : ℝ) < (b : ℝ) ∧ s = Set.Ioo (a : ℝ) (b : ℝ) }

/-- This collection satisfies the usual basis axioms: every point is in some basis
    element, and the intersection axiom for basis elements. -/
theorem rational_intervals_form_basis :
  (∀ x : ℝ, ∃ U, U ∈ rational_open_intervals ∧ x ∈ U) ∧
  (∀ U V, U ∈ rational_open_intervals → V ∈ rational_open_intervals →
    ∀ x, x ∈ U ∩ V → ∃ W, W ∈ rational_open_intervals ∧ x ∈ W ∧ W ⊆ U ∩ V) :=
  by sorry

/-- The topology generated by the rational-open-intervals. -/
def rational_open_topology : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom rational_open_intervals

/-- The lower limit (Sorgenfrey) basis: half-open intervals [a,b) with real endpoints. -/
def sorgenfrey_basis : Set (Set ℝ) :=
  { s | ∃ (a b : ℝ), a < b ∧ s = Set.Ico a b }

/-- The Sorgenfrey (lower limit) topology generated by the half-open intervals [a,b). -/
def sorgenfrey_topology : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom sorgenfrey_basis

/-- These two topologies are different. (One can show, for example, that points have
    different local bases; details omitted.) -/
theorem rational_topology_ne_sorgenfrey : rational_open_topology ≠ sorgenfrey_topology :=
  by sorry
