import Mathlib

open Set

/-- The lower limit topology (Sorgenfrey line) on ℝ: basis of half-open intervals [a,b). -/
def lower_limit_basis : Set (Set ℝ) := { s | ∃ a b : ℝ, a < b ∧ s = Set.Ico a b }

def lower_limit_topology : TopologicalSpace ℝ := TopologicalSpace.generateFrom lower_limit_basis

/-- The set K = {1/(n+1) | n ∈ ℕ}, used in the K-topology. -/
def K_set : Set ℝ := Set.range fun n : ℕ => (1 : ℝ) / (n + 1)

/-- The K-topology on ℝ: generated by all open intervals (a,b) and their complements removing K. -/
def K_basis : Set (Set ℝ) := { s | ∃ a b : ℝ, a < b ∧ (s = Set.Ioo a b ∨ s = (Set.Ioo a b) \ K_set) }

def K_topology : TopologicalSpace ℝ := TopologicalSpace.generateFrom K_basis

/-- The lower limit topology and the K-topology are not comparable: each has open sets not open
in the other. -/
theorem lower_limit_and_K_not_comparable :
  (∃ U : Set ℝ, @IsOpen ℝ lower_limit_topology U ∧ ¬ @IsOpen ℝ K_topology U) ∧
  (∃ V : Set ℝ, @IsOpen ℝ K_topology V ∧ ¬ @IsOpen ℝ lower_limit_topology V) := by sorry
