import Mathlib

/-!
Translate: Let n ≥ 2. Prove that S_n is generated by the two elements
S = { (1 2), (1 2 3 … n) }.

We state this as: there exists a permutation sigma (an n-cycle) of Fin n such that
the subgroup generated by the transposition (0 1) and sigma is the whole permutation group.
-/

theorem symmetric_group_generated_by_transposition_and_cycle (n : ℕ) (hn : 2 ≤ n) :
  ∃ sigma : Equiv.Perm (Fin n),
    Subgroup.closure ({Equiv.swap (Fin.ofNat n (by decide) 0), sigma} : Set (Equiv.Perm (Fin n))) =
      (⊤ : Subgroup (Equiv.Perm (Fin n))) := by sorry
