import Mathlib

/-!
Exercise 9.1.10 (Dummit--Foote):
Show that the ring Z[x1,x2,x3,...] / (x1*x2, x3*x4, x5*x6, ...) contains infinitely many minimal prime ideals.

We formalize the polynomial ring as MvPolynomial ℕ Int and the ideal I generated by the products X (2*k) * X (2*k+1) for k : ℕ.
The statement asserts the existence of an injective sequence of prime ideals of R containing I which are minimal over I.
-/

theorem Dummit_Foote_exercise_9_1_10 :
  ∃ (f : ℕ → Ideal (MvPolynomial ℕ Int)),
    Function.Injective f ∧
    (∀ n, (f n).IsPrime ∧
      Ideal.span (Set.range fun k => MvPolynomial.X (2 * k) * MvPolynomial.X (2 * k + 1))
        ≤ f n ∧ (∀ Q, Q.IsPrime → Ideal.span (Set.range fun k => MvPolynomial.X (2 * k) * MvPolynomial.X (2 * k + 1)) ≤ Q → Q ≤ f n → Q = f n)) := by
  sorry
