import Mathlib

variable {G : Type*} [Group G]

/--
Let G be a group such that all subgroups of G are normal.
If a, b ∈ G, then ba = a^j b for some integer j.
We encode the hypothesis that all subgroups are normal by requiring
that the cyclic subgroup generated by any element a is normal,
i.e. b * a * b⁻¹ ∈ Subgroup.zpowers a for all a, b.
-/
theorem Herstein_exercise_2_5_23 (h : ∀ a b : G, b * a * b⁻¹ ∈ Subgroup.zpowers a) (a b : G) :
  ∃ j : Int, b * a = (a ^ j) * b := by sorry
