import Mathlib

open Set

/-- The collection of open intervals with rational endpoints as a set of subsets of ℝ. -/
def rational_open_interval_basis : Set (Set ℝ) :=
  { s | ∃ (q1 q2 : ℚ), (↑q1 : ℝ) < (↑q2 : ℝ) ∧ s = Ioo (↑q1) (↑q2) }

/-- The collection of rational open intervals is a topological basis for the usual topology on ℝ. -/
theorem rational_open_intervals_is_basis : TopologicalSpace.IsTopologicalBasis rational_open_interval_basis := by sorry

/-- The topology generated by the rational open intervals is the standard topology on ℝ. -/
theorem rational_open_intervals_generate_standard_topology :
  TopologicalSpace.generateFrom rational_open_interval_basis = (inferInstance : TopologicalSpace ℝ) := by sorry
