import Mathlib

/-- Let H be the subgroup generated by two elements a, b of a group G. If a and b commute,
then the subgroup generated by a and b is abelian. -/
theorem Artin_exercise_2_2_9 {G : Type _} [Group G] (a b : G) (hab : a * b = b * a) :
  ∀ x y : G, x ∈ Subgroup.closure ({a, b} : Set G) → y ∈ Subgroup.closure ({a, b} : Set G) → x * y = y * x := by sorry
