import Mathlib

/-
The group given by the presentation <a, b | a^5 = b^2 = 1, ba = a^2 b>
is isomorphic to Z/2Z.  In particular, in any group G if a,b satisfy
these relations then a = 1 and the subgroup generated by a and b is
isomorphic to the group of order 2.  We state the result as a MulEquiv
between the subgroup generated by {a,b} and Multiplicative (ZMod 2).
-/

theorem srdoty_alg_present_315 {G : Type*} [Group G] (a b : G)
  (ha : a ^ 5 = 1) (hb : b ^ 2 = 1) (hconj : b * a = a ^ 2 * b) :
  (↥(Subgroup.closure ({a, b} : Set G))) ≃* Multiplicative (ZMod 2) := by sorry
