import Mathlib

open Equiv Equiv.Perm Subgroup List

/-- For n ≥ 2, the symmetric group on n letters is generated by the transposition (0 1)
    and the n-cycle (0 1 2 … n-1). -/
theorem symmetric_group_generated_by_transposition_and_cycle (n : ℕ) (hn : 2 ≤ n) :
  Subgroup.closure ({ swap (0 : Fin n) 1, cycle (List.range n) } : Set (Equiv.Perm (Fin n))) =
    (⊤ : Subgroup (Equiv.Perm (Fin n))) := by sorry
