import Mathlib
open Set Filter TopologicalSpace
open Filter Topology

/-- Show that if \mathcal{A} is a subbasis for a topology on X, then the topology generated by \mathcal{A} equals the intersection of all topologies on X that contain \mathcal{A}. -/
theorem generate_subbasis_eq_sInf {X : Type*} (𝒜 : Set (Set X)) (h𝒜 : IsSubbasis 𝒜) :
    generateFrom 𝒜 = sInf { t : TopologicalSpace X | ∀ U ∈ 𝒜, IsOpen t U } := by sorry
